version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://satellitezip_user:1@db:5432/satellitezip_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=satellitezip_db
      - POSTGRES_USER=satellitezip_user
      - POSTGRES_PASSWORD=1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
