version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://satellitezip_user:1@db:5432/satellitezip_db
      - REQUEST_LOGGING_FILE=/app/logs/request_logs.txt
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      petrov:
        ipv4_address: 10.20.2.2

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=satellitezip_db
      - POSTGRES_USER=satellitezip_user
      - POSTGRES_PASSWORD=1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      petrov:
        ipv4_address: 10.20.2.3

volumes:
  postgres_data:

networks:
  petrov:
    external: true
    name: petrov
