# Generated by Django 5.1.7 on 2025-04-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatellitePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('part_number', models.CharField(max_length=50, unique=True, verbose_name='S/N')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='manufacturer')),
                ('description', models.CharField(blank=True, verbose_name='desription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'spare part',
                'verbose_name_plural': 'spare parts',
            },
        ),
    ]
