# Generated by Django 5.1.7 on 2025-04-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitepart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
