name: Deploy SatelliteZip

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Fix Docker permissions
      run: |
        sudo groupadd docker || true
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Setup Docker
      run: |
        docker-compose down
        docker-compose up -d --build

    - name: Test application
      run: |
        curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:8000
