name: Deploy SatelliteZip

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Stop old containers
        run: |
          cd LAB3
          docker-compose down || true

      - name: Run containers
        run: |
          cd LAB3
          docker-compose up -d --build

      - name: Verify
        run: |
          curl --retry 3 --retry-delay 5 --retry-all-errors http://localhost:8000